---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment  # name of the manifest 
metadata:
  name: huguette-dev # This is the name of the APP/pods 
  namespace: josh # change this to your preferred namespace 
spec:
  selector:
    matchLabels:
      app: huguette-dev # The name of APP/pods - change this to your preferred APP name
  replicas: 4 # tells us the number of pods matching the template. In this case 1 pod/container/application
  strategy:
    type: RollingUpdate # Canary is the cheapest. All you do is change the name of the APP and keep same service.Bluegreen deployement strater but impotant for Disaster Recovery Plan.
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: huguette-dev # Change the name of APP
    spec:
      containers:
      - name: huguette-dev # Change name of container 
        image: nginx # This image will be given by the company - For demo use base image nginx 
        imagePullPolicy: Always 
        ports:
        - containerPort: 80 # This is the container port 
---
apiVersion: v1
kind: Service # service manifest 
metadata:
  name: huguette-services # load balancer and also expose the pods to the user on internet
  labels:
    app: huguette-dev
spec:
  selector:
    app: huguette-dev
  type: LoadBalancer
  ports:
    - port: 80 # container port 
      targetPort: 80 # same as container port 
      nodePort: 31300 # the entrance door to the node where the pods are installed. The nodeport ranges from 30000 ro 32767

